### ISSUE TITLE
Support multiple URLs in package.yml in go-task update

### ISSUE THREAD

**Issue by TraceyC77** [getsolus/ypkg#64]
We have packages that need multiple URLs such as yubico-authenticator
Feature request: Allow `go-task update` to handle more than one url

The package.yml for yubico-authenticator looks like:

```yaml
name       : yubico-authenticator
version    : 6.4.0
release    : 7
source     :
    - https://github.com/Yubico/yubioath-flutter/archive/refs/tags/6.4.0.tar.gz : cd0d4794205e386866872b945efdfb00fe514e1ff027f6f8c1c87d33dbb53c79
    - https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.16.5-stable.tar.xz#flutter.tar.xz : 57e59fa3a31be7e87b3847cdf782f1323578bbf70a0cd35f3615f01ab429ac29
homepage   : https://www.yubico.com/products/yubico-authenticator/
license    : BSD-2-Clause
component  : security
...
```

Currently, when running `go-task update -- $version $url`, the second URL is stripped from package.yml
This causes the build to fail
